services:
    server:
        build: .
        container_name: scriptowl-server
        env_file:
            - ./server/.env
        ports:
            - "5000:5000"
        develop:
            watch:
                - path: server
                  action: rebuild
                - path: types
                  action: rebuild
        image: jchen396/scriptowl-image:latest # Match the existing repo
