import type { NextRequest } from "next/server";

export const config = {
    runtime: "edge",
};

// Piped API instances (free, open-source YouTube proxy)
// These handle IP blocking by running their own proxy infrastructure
const PIPED_INSTANCES = [
    "https://pipedapi.kavin.rocks",
    "https://pipedapi.adminforge.de",
    "https://pipedapi.in.projectsegfau.lt",
];

// Direct innertube as a final fallback (works from non-blocked IPs / local dev)
const INNERTUBE_API_KEY = "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8";
const CONSENT_COOKIE = "SOCS=CAESEwgDEgk2ODE5MTAyNjUaAmVuIAEaBgiA_LyaBg";

function extractVideoId(url: string): string | null {
    const regex =
        /(?:youtube\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|\S+[\?\&]v=)|youtu\.be\/)([a-zA-Z0-9_-]{11})/;
    const match = url.match(regex);
    return match ? match[1] : null;
}

function decodeEntities(text: string): string {
    return text
        .replace(/&amp;/g, "&")
        .replace(/&lt;/g, "<")
        .replace(/&gt;/g, ">")
        .replace(/&#39;/g, "'")
        .replace(/&quot;/g, '"')
        .replace(/<[^>]*>/g, "")
        .trim();
}

/**
 * Parse VTT (WebVTT) subtitle format into plain text lines
 */
function parseVtt(vtt: string): string[] {
    const lines: string[] = [];
    const blocks = vtt.split("\n\n");

    for (const block of blocks) {
        const blockLines = block.trim().split("\n");
        // Skip the WEBVTT header and timestamp lines
        const textLines = blockLines.filter(
            (line) =>
                !line.startsWith("WEBVTT") &&
                !line.startsWith("Kind:") &&
                !line.startsWith("Language:") &&
                !line.startsWith("NOTE") &&
                !line.match(/^\d{2}:\d{2}/) && // timestamp lines
                !line.match(/^\d+$/) && // sequence numbers
                line.trim().length > 0
        );

        for (const textLine of textLines) {
            // Remove VTT tags like <c>, </c>, <00:00:01.000> etc.
            const cleaned = textLine
                .replace(/<[^>]*>/g, "")
                .trim();
            if (cleaned && !lines.includes(cleaned)) {
                lines.push(cleaned);
            }
        }
    }

    return lines;
}

/**
 * Parse XML subtitle format into plain text lines
 */
function parseXml(xml: string): string[] {
    const lines: string[] = [];
    const regex = /<text[^>]*>([\s\S]*?)<\/text>/g;
    let match;
    while ((match = regex.exec(xml)) !== null) {
        const text = decodeEntities(match[1]);
        if (text) lines.push(text);
    }
    return lines;
}

/**
 * Try fetching transcript via a Piped API instance
 */
async function tryPipedInstance(
    videoId: string,
    instance: string
): Promise<string | null> {
    try {
        const controller = new AbortController();
        const timeout = setTimeout(() => controller.abort(), 12000);

        const response = await fetch(`${instance}/streams/${videoId}`, {
            signal: controller.signal,
            headers: { Accept: "application/json" },
        });

        clearTimeout(timeout);

        if (!response.ok) {
            console.log(`[Piped ${instance}] HTTP ${response.status}`);
            return null;
        }

        const data = await response.json();

        if (!data.subtitles || data.subtitles.length === 0) {
            console.log(`[Piped ${instance}] No subtitles found`);
            return null;
        }

        // Find English subtitles
        const enSub =
            data.subtitles.find(
                (s: any) => s.code === "en" && !s.autoGenerated
            ) ||
            data.subtitles.find((s: any) => s.code === "en") ||
            data.subtitles[0];

        if (!enSub?.url) {
            console.log(`[Piped ${instance}] No English subtitle URL`);
            return null;
        }

        console.log(
            `[Piped ${instance}] Found subtitle: ${enSub.code} (auto=${enSub.autoGenerated})`
        );

        // Fetch the subtitle content
        const subResponse = await fetch(enSub.url, {
            headers: { Accept: "text/vtt, application/xml, text/xml, */*" },
        });

        if (!subResponse.ok) {
            console.log(
                `[Piped ${instance}] Subtitle fetch HTTP ${subResponse.status}`
            );
            return null;
        }

        const subContent = await subResponse.text();

        if (!subContent || subContent.length === 0) {
            console.log(`[Piped ${instance}] Empty subtitle content`);
            return null;
        }

        // Parse based on content type
        let lines: string[];
        if (subContent.includes("WEBVTT")) {
            lines = parseVtt(subContent);
        } else if (subContent.includes("<text")) {
            lines = parseXml(subContent);
        } else {
            // Try as plain text
            lines = subContent
                .split("\n")
                .map((l) => l.trim())
                .filter(Boolean);
        }

        if (lines.length === 0) {
            console.log(`[Piped ${instance}] No text extracted`);
            return null;
        }

        console.log(
            `[Piped ${instance}] SUCCESS — ${lines.length} lines`
        );
        return lines.join("\n");
    } catch (err: any) {
        console.log(`[Piped ${instance}] Error: ${err.message}`);
        return null;
    }
}

/**
 * Fallback: Try direct innertube API (works from non-cloud IPs)
 */
async function tryInnertube(videoId: string): Promise<string | null> {
    try {
        const response = await fetch(
            `https://www.youtube.com/youtubei/v1/player?key=${INNERTUBE_API_KEY}&prettyPrint=false`,
            {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "User-Agent":
                        "com.google.android.youtube/20.10.38 (Linux; U; Android 11) gzip",
                    "X-YouTube-Client-Name": "3",
                    "X-YouTube-Client-Version": "20.10.38",
                    Cookie: CONSENT_COOKIE,
                },
                body: JSON.stringify({
                    context: {
                        client: {
                            clientName: "ANDROID",
                            clientVersion: "20.10.38",
                            androidSdkVersion: 30,
                        },
                    },
                    videoId,
                }),
            }
        );

        if (!response.ok) return null;

        const data = await response.json();
        if (data?.playabilityStatus?.status !== "OK") {
            console.log(
                `[Innertube] status=${data?.playabilityStatus?.status}, reason=${data?.playabilityStatus?.reason}`
            );
            return null;
        }

        const tracks =
            data?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
        if (!tracks || tracks.length === 0) return null;

        const track =
            tracks.find(
                (t: any) => t.languageCode === "en" && t.kind !== "asr"
            ) ||
            tracks.find((t: any) => t.languageCode === "en") ||
            tracks[0];

        if (!track?.baseUrl) return null;

        const captionResponse = await fetch(
            track.baseUrl.replace("&fmt=srv3", ""),
            {
                headers: { Cookie: CONSENT_COOKIE },
            }
        );

        if (!captionResponse.ok) return null;

        const xml = await captionResponse.text();
        const lines = parseXml(xml);

        if (lines.length === 0) return null;

        console.log(`[Innertube] SUCCESS — ${lines.length} lines`);
        return lines.join("\n");
    } catch (err: any) {
        console.log(`[Innertube] Error: ${err.message}`);
        return null;
    }
}

export default async function handler(req: NextRequest) {
    if (req.method !== "POST") {
        return new Response(
            JSON.stringify({ error: "Method not allowed" }),
            { status: 405, headers: { "Content-Type": "application/json" } }
        );
    }

    let body: any;
    try {
        body = await req.json();
    } catch {
        return new Response(
            JSON.stringify({ error: "Invalid request body" }),
            { status: 400, headers: { "Content-Type": "application/json" } }
        );
    }

    const { youtubeURL } = body;
    if (!youtubeURL) {
        return new Response(
            JSON.stringify({ error: "youtubeURL is required" }),
            { status: 400, headers: { "Content-Type": "application/json" } }
        );
    }

    const videoId = extractVideoId(youtubeURL);
    if (!videoId) {
        return new Response(
            JSON.stringify({ error: "Invalid YouTube URL" }),
            { status: 400, headers: { "Content-Type": "application/json" } }
        );
    }

    // Strategy: Try Piped instances first, then direct innertube as fallback
    let transcript: string | null = null;

    // Try Piped instances
    for (const instance of PIPED_INSTANCES) {
        transcript = await tryPipedInstance(videoId, instance);
        if (transcript) break;
    }

    // Fallback to direct innertube (works on non-cloud IPs / local dev)
    if (!transcript) {
        transcript = await tryInnertube(videoId);
    }

    if (!transcript) {
        return new Response(
            JSON.stringify({
                error: "Failed to fetch transcript",
                details:
                    "Could not retrieve transcript from any source. The video may not have captions.",
            }),
            { status: 500, headers: { "Content-Type": "application/json" } }
        );
    }

    return new Response(
        JSON.stringify({ result: transcript }),
        { status: 200, headers: { "Content-Type": "application/json" } }
    );
}
